apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  labels:
    run: httpd-service
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30096
  selector:
    app: httpd-web
