apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-site-96
  labels:
    app: personal-site
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      app: personal-site
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: personal-site
    spec:
      containers:
      - name: personal-site-96
        image: nginx:1.7.9
        ports:
        - containerPort: 80

