apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rewrite-personal-site-96
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: my.aldialvayadi2-website.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: personal-site-96
                port:
                  number: 80
