apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-96
  labels:
    app: nginx-96
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      app: nginx-96
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx-96
    spec:
      nodeSelector:
        app_name: nginx-96
        kubernetes.io/hostname: student22-worker01
      containers:
      - name: nginx-96
        image: nginx:1.7.9
        ports:
        - containerPort: 80

